/*
 * Copyright (c) 2015 Tom Keffer <tkeffer@gmail.com>
 *
 *  See the file LICENSE for your full rights.
 */

/*
 * Subscribe all incoming websockets to all events generated by WeeRT
 */
"use strict";

var debug     = require('debug')('weert:server');
var socket_io = require('socket.io');

var event_list = [
    'platforms/POST',
    'platforms/PUT',
    'platforms/DELETE',
    'platforms/locations/POST',
    'platforms/locations/DELETE',
    'streams/POST',
    'streams/packets/POST',
    'streams/packets/DELETE'
];

var SocketIOFactory = function (http, app) {

    var io = socket_io(http);

    // Function for registering a socket for an event.
    // It will return a handle that can be used to unsubscribe to the event.
    var regEvent = function(socket, event){
        var f = function(data){
            socket.emit(event, data);
        };
        app.on(event, f);
        return f;
    };

    var unsubscribe_handles = {};
    /*
     * Listen for any new, incoming websocket connections, then subscribe
     * it to all known events.
     */
    io.on('connection', function (socket) {
        debug(new Date(), "A new client has connected");

        unsubscribe_handles[socket] = [];
        for (var i=0; i<event_list.length; i++){
            // Register to an event
            unsubscribe_handles[socket][i] = regEvent(socket, event_list[i]);
        }

        socket.on('disconnect', function () {
            // Websocket has disappeared. Unsubcribe it to all the events
            for (var i=0; i<event_list.length; i++){
                app.removeListener(event_list[i], unsubscribe_handles[socket][i]);
            }
            delete unsubscribe_handles[socket];
            // Use the first event as a surrogate for how many clients remain:
            debug(Date.now(), "A client has disconnected, leaving",
                app.listenerCount(event_list[0]), "subscriber(s)");
        });

        socket.emit('news', {msg: 'You are connected to the WeeRT server'});

    });

    return io;
};

module.exports = SocketIOFactory;